# -*- coding: utf-8 -*-
"""Task1(b).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGilsVwbJs9qDAcPyo9K2iW6pinBTR_m
"""

inf = open("input1b.txt", 'r')
outf = open("output1b.txt", 'w')

v, e = list(map(int, inf.readline().strip().split()))

ad_l = [[] for i in range(v+1)]

for i in range(e):
    f, t, w = list(map(int, inf.readline().strip().split()))
    ad_l[f].append((t, w))

for i in range(v+1):
    print(i, ":", end= " ", file=outf)
    for j in range(len(ad_l[i])):
        print(ad_l[i][j], end=" ", file=outf)
    print(file=outf)

inf.close()
outf.close()