# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CoIc0KgVH8R1GQ-1HndrHI4cOWhtvBRF
"""

file=open("input2.txt", "r")
text=file.read()
print(text)

inpath = "input2.txt"
infile = open(inpath, 'r')

outpath = "output2.txt"
outfile = open(outpath, 'w')

n = int(infile.readline().strip())

data = list(map(int, infile.readline().strip().split()))

def bubbleSort(arr):
    for i in range(len(arr)-1):
        swp = False
        for j in range(len(arr)-i-1):
            if arr[j] > arr[j+1]:
                arr[j], arr[j+1] = arr[j+1], arr[j]
                swp = True
        if(swp == False):
            break

    return arr

for i in (bubbleSort(data)):
    outfile.write(f'{i} ')
"""

To achieve a best-case time complexity of θ(n) for the Bubble Sort algorithm,
the array should already be sorted. In the best-case scenario,
the array is in ascending order, and no swaps are required during the sorting process.

"""