# -*- coding: utf-8 -*-
"""Task5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HtrU_3J96o386ggkZzcr55BZWPr4vVhx
"""

import random

inf = open("input5.txt", 'r')
outf = open("output5.txt", 'w')

n = int(inf.readline().strip())
data = list(map(int, (inf.readline().strip().split())))


def qck_srt(data):

    if len(data) == 1:
        return data
    if len(data) > 0:
      pvt = random.randint(0, len(data)-1)
    else:
      pvt=None

    if pvt is not None:
        l = [x for x in data if x < data[pvt]]
        mid = [y for y in data if y == data[pvt]]
        r = [z for z in data if z > data[pvt]]

        srt_l = qck_srt(l)
        srt_r = qck_srt(r)

        return srt_l + mid + srt_r

    else:
        return []

for x in qck_srt(data):
    outf.write(str(x) + ' ')

inf.close()
outf.close()