# -*- coding: utf-8 -*-
"""Task2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6HCLOaSF-jlCCF_t-xQx5aj98h0fXEB
"""

import math

inf = open("input2.txt", 'r')
outf = open("output2.txt", 'w')
n = int(inf.readline().strip())
d = list(map(int, (inf.readline().strip().split())))

def dvd_nd_cnqr(d, max_val = -math.inf):
    if len(d) == 1:
        return d, d[0]

    elif len(d) == 2:
        if d[0] > d[1]:
            max_val = d[0]
        else:
            max_val = d[1]
        return d, max_val

    mid = len(d) // 2
    l = dvd_nd_cnqr(d[:mid], max_val)
    r = dvd_nd_cnqr(d[mid:], max_val)

    if l[1] > r[1]:
        max_val = l[1]
    else:
        max_val = r[1]

    return l[0] + r[0], max_val

outf.write(str(dvd_nd_cnqr(d)[1]))


inf.close()
outf.close()