# -*- coding: utf-8 -*-
"""Task2a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7JHAQ_67ZGx30wd-cawmAyfyVSyHsIU
"""

str1="input2a.txt"
str2="output2a.txt"
inp=open(str1,"r")
otp=open(str2,"w")
leng1=int(inp.readline())
arr1=inp.readline().split()
leng2=int(inp.readline())
arr2=inp.readline().split()
k=leng1+leng2
arr3=[None]*k
for x in range(leng1):
  arr3[x]=int(arr1[x])
z=0
for y in range(leng1,k):
  arr3[y]=int(arr2[z])
  z+=1
def sorting(para):

  if len(para)<=1:
    return para
  else:
    mid=len(para)//2
    a=sorting(para[:mid])
    b=sorting(para[mid:])

    arr=[None]*len(para)
    l=0
    i=0
    j=0


    while l<len(para):
        if i!=len(a) and j !=len(b):
            if a[i]<b[j]:
                arr[l]=a[i]
                i+=1
            elif a[i]>b[j]:
                arr[l]=b[j]
                j+=1
            else:
                arr[l]=a[i]
                l+=1
                arr[l]=b[j]
                i+=1
                j+=1

        else:
            if i==len(a):
                arr[l]=b[j]
                j+=1
            else:
                arr[l]=a[i]
                i+=1
        l+=1

    return(arr)


otp.write(str(sorting(arr3)))


inp.close()
otp.close()