# -*- coding: utf-8 -*-
"""Task4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CoIc0KgVH8R1GQ-1HndrHI4cOWhtvBRF
"""

file=open("input1(b).txt", "r")
text=file.read()
print(text)

inpath = "input1(b).txt"
file = open(inpath, 'r')

outpath = "output1b.txt"
file2 = open(outpath, 'w')

n = file.readline().strip()

for i in range(int(n)):
    temp = file.readline().strip().split()
    if '+' in temp:
        file2.write(f'The result of {int(temp[1])} + {int(temp[3])} is {int(temp[1])+int(temp[3])}\n')
    elif '-' in temp :
        file2.write(f'The result of {int(temp[1])} - {int(temp[3])} is {int(temp[1])-int(temp[3])}\n')
    elif '*' in temp :
        file2.write(f'The result of {int(temp[1])} * {int(temp[3])} is {int(temp[1])*int(temp[3])}\n')
    else:
        file2.write(f'The result of {int(temp[1])} / {int(temp[3])} is {int(temp[1])/int(temp[3])}\n')

file.close()
file2.close()