# -*- coding: utf-8 -*-
"""Task1a.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7JHAQ_67ZGx30wd-cawmAyfyVSyHsIU
"""

f1=open('input1a.txt', 'r')
f2=open('output1a.txt', 'w')
n, t = list(map(int, (f1.readline().strip().split())))
k=list(map(int, (f1.readline().strip().split())))
possible=False
for i in range (n):
  for j in range (i+1, n):
    if k[i]+k[j]==t:
      f2.write(f'{i+1} {j+1}')
      possible=True
  if possible :
    break
if not possible:
  f2.write('IMPOSSIBLE')
f2.close()