# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1CoIc0KgVH8R1GQ-1HndrHI4cOWhtvBRF
"""

file=open("input3.txt", "r")
text=file.read()
print(text)

inpath = "input3.txt"
infile = open(inpath, 'r')

outpath = "output3.txt"
outfile = open(outpath, 'w')

n = int(infile.readline().strip())
id = list(map(int, infile.readline().strip().split()))
mark = list(map(int, infile.readline().strip().split()))

for i in range(n):
    min_idx = i
    for j in range(i+1, n):
        if mark[min_idx] < mark[j]:
            min_idx = j

        if mark[min_idx] == mark[j]:
            if id[min_idx] > id[j]:
                min_idx = j

    mark[i], mark[min_idx] = mark[min_idx], mark[i]
    id[i], id[min_idx] = id[min_idx], id[i]

for i in range(n):
    outfile.write(f'ID: {id[i]} Mark: {mark[i]}\n')

infile.close()
outfile.close()