# -*- coding: utf-8 -*-
"""Task1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E6HCLOaSF-jlCCF_t-xQx5aj98h0fXEB
"""

inf = open("input1.txt", 'r')
outf = open("output1.txt", 'w')

n = int(inf.readline().strip())
data = list(map(int, (inf.readline().strip().split())))

def mrg_srt(data):
    if len(data) <= 1:
        return data

    mid = len(data) // 2
    srt_l = mrg_srt(data[:mid])
    srt_r = mrg_srt(data[mid:])
    srt_data = []

    i, j = 0, 0
    while i < len(srt_l) and j < len(srt_r):
        if srt_l[i] < srt_r[j]:
            srt_data.append(srt_l[i])
            i += 1
        elif srt_l[i] > srt_r[j]:
            srt_data.append(srt_r[j])
            j += 1

        else:
            srt_data.append(srt_l[i])
            srt_data.append(srt_r[j])
            i += 1
            j += 1

    if i != len(srt_l):
        srt_data.extend(srt_l[i:])
    else:
        srt_data.extend(srt_r[j:])

    return srt_data

answer = mrg_srt(data)

for i in answer:
    outf.write(f"{i} ")

inf.close()
outf.close()