# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGilsVwbJs9qDAcPyo9K2iW6pinBTR_m
"""

inf = open("input3.txt", 'r')
outf = open("output3.txt", 'w')
v, e = list(map(int, inf.readline().strip().split()))
visit = [0 for i in range(v+1)]
ad_l = [[]for i in range(v+1)]
for i in range(e):
    f, t = list(map(int, inf.readline().strip().split()))
    ad_l[f].append(t)
    ad_l[t].append(f)

def DFS_trvrs(ad_l, select):
    visit[select] = 1
    print(select, end=" ", file=outf)
    for ad_nd in ad_l[select]:
        if visit[ad_nd] == 0:
            DFS_trvrs(ad_l, ad_nd)
select = 1
DFS_trvrs(ad_l, select)
inf.close()
outf.close()