# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-qCDcd7HPu9WDt7sxRYf-QM0vx3oIiZS
"""

inf = open("input3.txt", 'r')
outf = open("output3.txt", 'w')
def find_rprsnttv(a):
    if prnt[a] == a:
        return a
    return find_rprsnttv(prnt[a])

def union(a, b):
    u = find_rprsnttv(a)
    v = find_rprsnttv(b)
    if u != v:
        prnt[u] = v
        crcl[v] += crcl[u]
    outf.write(str(crcl[v]) + '\n')

prsn, query = map(int, inf.readline().split())
prnt = [ i for i in range(prsn) ]
crcl = [ 1 for i in range(prsn) ]
for i in range(query):
    a, b = map(int, inf.readline().split())
    union(a, b)

inf.close()
outf.close()