# -*- coding: utf-8 -*-
"""Task3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E7JHAQ_67ZGx30wd-cawmAyfyVSyHsIU
"""

inf=open('input3.txt','r')
otf=open('output3.txt','w')
n=int(inf.readline())
li=[]
li1=[]
temp=0
count=0
for i in range(n):
  a=inf.readline()
  tup=tuple(map(int,a.split()))
  li.append(tup)
for i in range(n):
  for j in range(n-i-1):
    if li[j][1]>li[j+1][1]:
      li[j],li[j+1]=li[j+1],li[j]
for i in li:
  start_time,end_time=i[0],i[1]
  if start_time>=temp:
    li1.append(i)
    temp=end_time
    count+=1
otf.write(f'{str(count)}\n')
for i in li1:
  otf.write(f'{i[0]} {i[1]}\n')


inf.close()
otf.close()