# -*- coding: utf-8 -*-
"""Task1(a).ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1iGilsVwbJs9qDAcPyo9K2iW6pinBTR_m
"""

inf = open("input1a.txt", 'r')
outf = open("output1a.txt", 'w')

v, e = list(map(int, inf.readline().strip().split()))

ad_mat = [[0 for i in range(v+1)] for j in range(v+1)]

for i in range(e):
    f, t, w =  list(map(int, inf.readline().strip().split()))
    ad_mat[f][t] = w

for i in range(v+1):
    for j in range(v+1):
        outf.write(str(ad_mat[i][j]) + " ")
    outf.write("\n")